'use strict';

var Constants = {
	LOAD_NEWS_LIST_SUCCESS:'LOAD_NEWS_LIST_SUCCESS',
	LOAD_BOOK_LIST_SUCCESS:'LOAD_BOOK_LIST_SUCCESS',
	
	LOAD_FAIL:'LOAD_FAIL',

  	ADD_CART: 'ADD_CART',
  	DELETE_CART: 'DELETE_CART'
};
module.exports=Constants;